/** 常用城市 */
var commoncitys = [];
commoncitys.push(['CAN', '广州', 'GUANGZHOU', 'GZ']);
commoncitys.push(['SZX', '深圳', 'SHENZHEN', 'SZ']);
commoncitys.push(['PEK', '北京', 'BEIJING', 'BJ']);
commoncitys.push(['SHA', '上海', 'SHANGHAI', 'SH']);
commoncitys.push(['CTU', '成都', 'CHENGDU', 'CD']);
commoncitys.push(['HGH', '杭州', 'HANGZHOU', 'HZ']);
commoncitys.push(['CSX', '长沙', 'CHANGSHA', 'CS']);
commoncitys.push(['CKG', '重庆', 'CHONGQING', 'CQ']);
commoncitys.push(['KMG', '昆明', 'KUNMING', 'KM']);
commoncitys.push(['XIY', '西安', 'XIAN', 'XA']);
commoncitys.push(['WUH', '武汉', 'WUHAN', 'WH']);
commoncitys.push(['NKG', '南京', 'NANJING', 'NJ']);
commoncitys.push(['TAO', '青岛', 'QINGDAO', 'QD']);
commoncitys.push(['SYX', '三亚', 'SANYA', 'SY']);
commoncitys.push(['XMN', '厦门', 'XIAMEN', 'XM']);

/** 所有城市 */
var citys = [];
citys.push(['SHA', '上海', 'SHANGHAI', 'SH']);
citys.push(['HYN', '黄岩(台州)', 'HUANGYAN', 'HY']);
citys.push(['HGH', '杭州', 'HANGZHOU', 'HZ']);
citys.push(['YIW', '义乌', 'YIWU', 'YW']);
citys.push(['JUZ', '衢州', 'JUZHOU', 'QZ']);
citys.push(['HSN', '舟山(普陀山)', 'ZHOUSHAN', 'ZS']);
citys.push(['WNZ', '温州', 'WENZHOU', 'WZ']);
citys.push(['NGB', '宁波', 'NINGBO', 'NB']);
citys.push(['WNH', '文山壮族苗族自治州', 'PUZHEHE', '']);
citys.push(['LNJ', '临沧', 'LINCANG', 'LC']);
citys.push(['ZAT', '昭通', 'ZHAOTONG', 'ZT']);
citys.push(['SYM', '思茅', 'SIMAO', 'SM']);
citys.push(['LUM', '芒市', 'MANSHI', 'MS']);
citys.push(['BSD', '保山', 'BAOSHAN', 'BS']);
citys.push(['KMG', '昆明', 'KUNMING', 'KM']);
citys.push(['JHG', '西双版纳', 'XISHUANGBANNA', 'XSBN']);
citys.push(['DLU', '大理', 'DALI', 'DL']);
citys.push(['TCZ', '腾冲', 'TENGCHONG', '']);
citys.push(['DIG', '迪庆', 'DIQING', 'DQ']);
citys.push(['LJG', '丽江', 'LIJIANG', 'LJ']);
citys.push(['BPX', '昌都地区', 'BANGDA', '']);
citys.push(['LXA', '拉萨', 'LASA', 'LS']);
citys.push(['LZY', '林芝', 'LINZHI', '']);
citys.push(['NLT', '新源', 'XINYUAN', '']);
citys.push(['TCG', '塔城', 'TACHENG', 'TC']);
citys.push(['IQM', '且末', 'QIEMO', 'QM']);
citys.push(['KCA', '库车', 'KUCHE', 'KC']);
citys.push(['HTN', '和田', 'HETAN', 'HT']);
citys.push(['HMI', '哈密', 'HAMI', 'HM']);
citys.push(['FYN', '富蕴', 'FUYUN', 'FY']);
citys.push(['AKU', '阿克苏', 'AGESU', 'AKS']);
citys.push(['URC', '乌鲁木齐', 'WULUMUQI', 'WLMQ']);
citys.push(['KHG', '喀什', 'KASHI', 'KS']);
citys.push(['KJI', '喀纳斯', 'KANASI', 'KNS']);
citys.push(['KRL', '库尔勒', 'KUERLE', 'KEL']);
citys.push(['KRY', '克拉玛依', 'KELAMAYI', 'KLMY']);
citys.push(['AAT', '阿勒泰', 'ALETAI', 'ALT']);
citys.push(['YIN', '伊宁', 'YINING', 'YN']);
citys.push(['TSN', '天津', 'TIANJIN', 'TJ']);
citys.push(['AKA', '安康', 'ANKANG', 'AK']);
citys.push(['ENY', '延安', 'YANAN', 'YA']);
citys.push(['HZG', '汉中', 'HANZHONG', 'HZ']);
citys.push(['XIY', '西安', 'XIAN', 'XA']);
citys.push(['UYN', '榆林', 'YULIN', 'YL']);
citys.push(['CIH', '长治', 'CHANGZHI', 'CZ']);
citys.push(['TYN', '太原', 'TAIYUAN', 'TY']);
citys.push(['DAT', '大同', 'DATONG', 'DT']);
citys.push(['YCU', '运城', 'YUNCHENG', 'YC']);
citys.push(['TNA', '济南', 'JINAN', 'JN']);
citys.push(['YNT', '烟台', 'YANTAI', 'YT']);
citys.push(['JNG', '济宁', 'JINING', 'JL']);
citys.push(['DOY', '东营', 'DONGYING', 'DY']);
citys.push(['LYI', '临沂', 'LINYI', 'LY']);
citys.push(['WEF', '潍坊', 'WEIFANG', 'WF']);
citys.push(['TAO', '青岛', 'QINGDAO', 'QD']);
citys.push(['WEH', '威海', 'WEIHAI', 'WH']);
citys.push(['KGT', '康定', 'KANGDING', '']);
citys.push(['GHN', '广汉', 'GUANGHAN', 'GH']);
citys.push(['DAX', '达州', 'DAXIAN', 'DX']);
citys.push(['CTU', '成都', 'CHENGDU', 'CD']);
citys.push(['MIG', '绵阳', 'MIANYANG', 'MY']);
citys.push(['YBP', '宜宾', 'YIBIN', 'YB']);
citys.push(['LZO', '泸州', 'LUZHOU', 'LZ']);
citys.push(['GYS', '广元', 'GUANGYUAN', '']);
citys.push(['XIC', '西昌', 'XICHANG', 'XC']);
citys.push(['NAO', '南充', 'NANCHONG', 'NC']);
citys.push(['JZH', '九寨沟', 'JIUZHAIGOU', 'JZG']);
citys.push(['PZI', '攀枝花', 'PANZHIHUA', 'PZH']);
citys.push(['YUS', '玉树', 'YUSHU', 'YS']);
citys.push(['GOQ', '格尔木', 'GELANMU', 'GEM']);
citys.push(['XNN', '西宁', 'XINING', 'XN']);
citys.push(['ZHY', '中卫', 'ZHONGWEI', '']);
citys.push(['INC', '银川', 'YINCHUAN', 'YC']);
citys.push(['ERL', '二连浩特', 'ERLIANHAOTE', 'ELHT']);
citys.push(['XIL', '锡林浩特', 'XILINHAOTE', 'XLHT']);
citys.push(['HLH', '乌兰浩特', 'WULANHAOTE', 'WLHT']);
citys.push(['WUA', '乌海', 'WUHAI', 'WH']);
citys.push(['TGO', '通辽', 'TONGLIAO', 'TL']);
citys.push(['HET', '呼和浩特', 'HUHEHAOTE', 'HHHT']);
citys.push(['DSN', '鄂尔多斯', 'EERDUOSI', 'EEDS']);
citys.push(['NZH', '满洲里', 'MANZHOULI', 'MZL']);
citys.push(['HLD', '海拉尔', 'HAILAER', 'HLE']);
citys.push(['CIF', '赤峰', 'CHIFENG', 'CF']);
citys.push(['BAV', '包头', 'BAOTOU', 'BT']);
citys.push(['CHG', '朝阳', 'CHAOYANG', 'CY']);
citys.push(['SHE', '沈阳', 'SHENYANG', 'SY']);
citys.push(['DLC', '大连', 'DALIAN', 'DL']);
citys.push(['DDG', '丹东', 'DANDONG', 'DD']);
citys.push(['JNZ', '锦州', 'JINZHOU', 'JZ']);
citys.push(['AOG', '鞍山', 'ANSHAN', 'AS']);
citys.push(['KHN', '南昌', 'NANCHANG', 'NC']);
citys.push(['JDZ', '景德镇', 'JINDEZHEN', 'JDZ']);
citys.push(['JIU', '九江', 'JIUJIANG', 'JJ']);
citys.push(['KOW', '赣州', 'GANZHOU', 'GZ']);
citys.push(['', '抚州', '', '']);
citys.push(['JGS', '井冈山', 'JINGGANGSHAN', 'JGS']);
citys.push(['KNC', '吉安', 'JIAN', 'JA']);
citys.push(['LYG', '连云港', 'LIANYUNGANG', 'LYG']);
citys.push(['SZV', '苏州', 'SUZHOU', 'SZ']);
citys.push(['YNZ', '盐城', 'YANCHENG', 'YC']);
citys.push(['XUZ', '徐州', 'XUZHOU', 'XZ']);
citys.push(['NKG', '南京', 'NANJING', 'NJ']);
citys.push(['NTG', '南通', 'NANTONG', 'NT']);
citys.push(['CZX', '常州', 'CHANGZHOU', 'CZ']);
citys.push(['WUX', '无锡', 'WUXI', 'WX']);
citys.push(['NBS', '白山', 'CHANGBAISHAN', '']);
citys.push(['TNH', '通化', 'TONGHUA', 'TH']);
citys.push(['JIL', '吉林', 'JILIN', 'JL']);
citys.push(['CGQ', '长春', 'CHANGCHUN', 'CC']);
citys.push(['YNJ', '延吉', 'YANJI', 'YJ']);
citys.push(['DYG', '张家界', 'ZHANGJIAJIE', 'ZJJ']);
citys.push(['CGD', '常德', 'CHANGDE', 'CD']);
citys.push(['LLF', '永州', 'LINGLING', '']);
citys.push(['HJJ', '怀化', 'HUAIHUA', 'HH']);
citys.push(['CSX', '长沙', 'CHANGSHA', 'CS']);
citys.push(['HNY', '衡阳', 'HENGYANG', 'HY']);
citys.push(['LDS', '伊春', 'YICHUN', 'YC']);
citys.push(['JXA', '鸡西', 'JIXI', 'JX']);
citys.push(['OHE', '漠河', 'MOHE', 'MH']);
citys.push(['HRB', '哈尔滨', 'HAERBIN', 'HRB']);
citys.push(['HEK', '黑河', 'HEIHE', 'HH']);
citys.push(['NDG', '齐齐哈尔', 'QIQIHAER', 'QQHE']);
citys.push(['JMU', '佳木斯', 'JIAMUSI', 'JMS']);
citys.push(['DQA', '大庆', 'DAQING', 'DQ']);
citys.push(['MDG', '牡丹江', 'MUDANJIANG', 'MDJ']);
citys.push(['LYA', '洛阳', 'LUOYANG', 'LY']);
citys.push(['NNY', '南阳', 'NANYANG', 'NY']);
citys.push(['CGO', '郑州', 'ZHENGZHOU', 'ZZ']);
citys.push(['SJW', '石家庄', 'SHIJIAZHUANG', 'SJZ']);
citys.push(['SHP', '秦皇岛', 'QINHUANGDAO', 'QHD']);
citys.push(['HDG', '邯郸', 'HANDAN', 'HD']);
citys.push(['SHS', '沙市', 'SHASHI', 'SS']);
citys.push(['WUH', '武汉', 'WUHAN', 'WH']);
citys.push(['XFN', '襄樊', 'XIANGFAN', 'XF']);
citys.push(['ENH', '恩施', 'ENSHI', 'ES']);
citys.push(['YIH', '宜昌', 'YICHANG', 'YC']);
citys.push(['HAK', '海口', 'HAIKOU', 'HK']);
citys.push(['SYX', '三亚', 'SANYA', 'SY']);
citys.push(['LLB', '荔波', 'LIBO', 'LB']);
citys.push(['XYI', '兴义', 'XINGYI', 'XY']);
citys.push(['KWE', '贵阳', 'GUIYANG', 'GY']);
citys.push(['TEN', '铜仁', 'TONGREN', 'TR']);
citys.push(['ZYI', '遵义', 'ZUNYI', 'ZY']);
citys.push(['BHY', '北海', 'BEIHAI', 'BH']);
citys.push(['KWL', '桂林', 'GUILIN', 'GL']);
citys.push(['LZH', '柳州', 'LIUZHOU', 'LZ']);
citys.push(['NNG', '南宁', 'NANNING', 'NN']);
citys.push(['AEB', '百色', 'BAISE', 'BS']);
citys.push(['WUZ', '梧州', 'WUZHOU', 'WZ']);
citys.push(['THQ', '天水', 'TIANSHUI', '']);
citys.push(['IQN', '庆阳', 'QINGYANG', 'QY']);
citys.push(['CHW', '酒泉', 'JIUQUAN', 'JQ']);
citys.push(['JGN', '嘉峪关', 'JIAYUGUAN', 'JYG']);
citys.push(['DNH', '敦煌', 'DUNHUANG', 'DH']);
citys.push(['LHW', '兰州', 'LANZHOU', 'LZ']);
citys.push(['ZHA', '湛江', 'ZHANJIANG', 'ZJ']);
citys.push(['MXZ', '梅州', 'MEIZHOU', 'MZ']);
citys.push(['ZUH', '珠海', 'ZHUHAI', 'ZH']);
citys.push(['FUO', '佛山', 'FOSHAN', 'FS']);
citys.push(['SWA', '汕头', 'SHANTOU', 'ST']);
citys.push(['SZX', '深圳', 'SHENZHEN', 'SZ']);
citys.push(['CAN', '广州', 'GUANGZHOU', 'GZ']);
citys.push(['XMN', '厦门', 'XIAMEN', 'XM']);
citys.push(['WUS', '武夷山', 'WUYISHAN', 'WYS']);
citys.push(['QHU', '泉州', 'QUANZHOU', 'QZ']);
citys.push(['LIC', '连城', 'LIANCHENG', 'LC']);
citys.push(['JJN', '晋江', 'JINJIANG', 'JJ']);
citys.push(['FOC', '福州', 'FUZHOU', 'FZ']);
citys.push(['CKG', '重庆', 'CHONGQING', 'CQ']);
citys.push(['TXN', '黄山', 'HUANGSHAN', 'HS']);
citys.push(['BFU', '蚌埠', 'BENGBU', 'BB']);
citys.push(['FUG', '阜阳', 'FUYANG', 'FY']);
citys.push(['HFE', '合肥', 'HEFEI', 'HF']);
citys.push(['AQG', '安庆', 'ANQING', 'AQ']);
citys.push(['PEK', '北京', 'BEIJING', 'BJ']);
// 根据三字码查找城市
function getCityByThreeWord(threeWord) {
    var cityCn = "";
    for (var i = 0, len = citys.length; i < len; i++) {
        if (threeWord == citys[i][0]) {
            cityCn = citys[i][1];
            break;
        }
    }
    return cityCn;
}
// 根据城市查找三字码
function getThreeWordByCity(cityName) {
    var threeWord = "";
    for (var i = 0, len = citys.length; i < len; i++) {
        if (cityName == citys[i][1]) {
            threeWord = citys[i][0];
            break;
        }
    }
    return threeWord;
}
